

/gate/physics/addPhysicsList emstandard_opt4

/gate/physics/Gamma/SetCutInRegion      world  1 m
/gate/physics/Electron/SetCutInRegion   world  1 m
/gate/physics/Positron/SetCutInRegion   world  1 m

/gate/physics/Gamma/SetCutInRegion      phantom  0.1 mm
/gate/physics/Electron/SetCutInRegion   phantom  0.1 mm
/gate/physics/Positron/SetCutInRegion   phantom  0.1 mm

/gate/physics/Gamma/SetCutInRegion      bed  0.1 mm
/gate/physics/Electron/SetCutInRegion   bed  0.1 mm
/gate/physics/Positron/SetCutInRegion   bed  0.1 mm

/gate/physics/Gamma/SetCutInRegion      crystal  0.1 mm
/gate/physics/Electron/SetCutInRegion   crystal  0.1 mm
/gate/physics/Positron/SetCutInRegion   crystal  0.1 mm
