
# Output: projection images
/gate/output/projection/enable
/gate/output/projection/setFileName output/projection

/gate/output/projection/addInputDataName scatter1
/gate/output/projection/addInputDataName peak113
/gate/output/projection/addInputDataName scatter2
/gate/output/projection/addInputDataName scatter3
/gate/output/projection/addInputDataName peak208
/gate/output/projection/addInputDataName scatter4
#/gate/output/projection/addInputDataName spectrum

/gate/output/projection/pixelSizeX 4.41806 mm
/gate/output/projection/pixelSizeY 4.41806 mm
/gate/output/projection/pixelNumberX 128
/gate/output/projection/pixelNumberY 128
/gate/output/projection/projectionPlane XY

