#.................... SCANNER DATA PROCESSING PARAMETERS
#       ADDER
# The adder output is a pulse that is an energy weighted centroid for the different hit positions within each crystal volume invlved in the event
/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/insert adder
#/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/adder/verbose 0
#/gate/digitizerMgr/convertor/verbose 0

# READOUT

# The redout regroups the pulsed per group of sensitive detectors
# defined by the depth in the volume hierarchy. The energy is the
# total energy in the stack and the position of the pulse with the
# maximun energy.

/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/insert readout
/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/readout/setDepth 1


# NOISE  

/gate/distributions/name energy_distrib 
/gate/distributions/insert Gaussian 
/gate/distributions/energy_distrib/setMean 500 keV 
/gate/distributions/energy_distrib/setSigma 1 keV

/gate/distributions/name dt_distrib 
/gate/distributions/insert Exponential 
/gate/distributions/dt_distrib/setLambda 2.1701 us

/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/insert noise 
/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/noise/setDeltaTDistribution dt_distrib 
/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/noise/setEnergyDistribution energy_distrib


# ENERGY BLURRING
/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/insert energyResolution 
/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/energyResolution/fwhmMin 0.112
/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/energyResolution/fwhmMax 0.112
/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/insert efficiency
/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/efficiency/setUniqueEfficiency 0.865
/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/energyResolution/energyOfReference 511. keV 


# TEMPORAL RESOLUTION
/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/insert timeResolution
/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/timeResolution/fwhm 220.0 ps
/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/timeResolution/verbose 0


# PILES-UP
/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/insert pileup 
/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/pileup/setDepth 1
/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/pileup/setPileup 5.9 ns


# DEADTIME
/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/insert deadtime  
/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/deadtime/setDeadTime 5.9 ns
/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/deadtime/setMode paralysable
/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/deadtime/chooseDTVolume module


# HIGH ENERGY CUT  
/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/insert energyFraming  
/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/energyFraming/setMin 0.44968 MeV
/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/energyFraming/setMax 0.61320 MeV


# COINCIDENCES SORTER
/gate/digitizerMgr/CoincidenceSorter/Coincidences/setInputCollection Singles 
#/gate/digitizerMgr/CoincidenceSorter/Coincidences/verbose 0
/gate/digitizerMgr/CoincidenceSorter/Coincidences/setWindow 2.0115 ns
/gate/digitizerMgr/CoincidenceSorter/Coincidences/minSectorDifference 5
/gate/digitizerMgr/CoincidenceSorter/Coincidences/MultiplesPolicy takeAllGoods

##Uncomment for second method for coincidence sorting
/gate/digitizerMgr/CoincidenceSorter/Coincidences/allDigiOpenCoincGate true

/gate/digitizerMgr/name Delay
/gate/digitizerMgr/insert CoincidenceSorter
/gate/digitizerMgr/CoincidenceSorter/Delay/setInputCollection Singles
/gate/digitizerMgr/CoincidenceSorter/Delay/setWindow 2.0115 ns
/gate/digitizerMgr/CoincidenceSorter/Delay/setOffset 100.0 ns #... it should be 100 ns
/gate/digitizerMgr/CoincidenceSorter/Delay/minSectorDifference 5
/gate/digitizerMgr/CoincidenceSorter/Delay/MultiplesPolicy takeAllGoods

##Uncomment for second method for coincidence sorting
/gate/digitizerMgr/CoincidenceSorter/Delay/allDigiOpenCoincGate true

