/gate/world/geometry/setXLength 20 cm
/gate/world/geometry/setYLength 20 cm
/gate/world/geometry/setZLength 40 cm
/gate/world/vis/setVisible 0
/gate/world/setMaterial Vacuum

/gate/world/daughters/name scanner
/gate/world/daughters/systemType scanner
/gate/world/daughters/insert box
/gate/scanner/placement/setTranslation 0 0 15 cm
/gate/scanner/geometry/setXLength 20 cm
/gate/scanner/geometry/setYLength 20 cm
/gate/scanner/geometry/setZLength 10 cm
/gate/scanner/vis/setColor red
/gate/scanner/vis/setVisible 1

/gate/scanner/daughters/name crystal
/gate/scanner/daughters/insert box
/gate/crystal/setMaterial Super_dense
/control/doif {filter_id} > 9 /gate/crystal/setMaterial PWO
/gate/crystal/placement/setTranslation 0 0 0 cm
/gate/crystal/geometry/setXLength 20 cm
/gate/crystal/geometry/setYLength 20 cm
/gate/crystal/geometry/setZLength 10 cm

/gate/world/daughters/name phantom
/gate/world/daughters/insert box
/gate/phantom/placement/setTranslation 0 0 0 cm
/gate/phantom/geometry/setXLength 20 cm
/gate/phantom/geometry/setYLength 20 cm
/gate/phantom/geometry/setZLength 1 cm
/gate/phantom/vis/setColor blue
/gate/phantom/vis/setVisible 1
/gate/phantom/setMaterial Vacuum

/gate/phantom/daughters/name phantom_part
/gate/phantom/daughters/insert box
/gate/phantom_part/placement/setTranslation 5 0 0 cm
/gate/phantom_part/geometry/setXLength 10 cm
/gate/phantom_part/geometry/setYLength 20 cm
/gate/phantom_part/geometry/setZLength 1 cm
/gate/phantom_part/vis/setColor red
/gate/phantom_part/vis/setVisible 1
/gate/phantom_part/setMaterial Vacuum

/gate/crystal/attachCrystalSD
/gate/systems/scanner/level1/attach crystal
/gate/phantom/attachPhantomSD
/gate/phantom_part/attachPhantomSD

#/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/insert adder
#/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/insert readout
#/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/readout/setDepth 1