
/gate/output/tree/enable
#/gate/output/tree/addFileName ./output/filter_id_{filter_id}.txt
/gate/output/tree/addFileName ./output/filter_id_{filter_id}.npy
/gate/output/tree/hits/enable

#PDGEncoding,trackID,parentID,trackLocalTime,time,runID,eventID,sourceID,primaryID,posX,posY,posZ,localPosX,localPosY,localPosZ,momDirX,momDirY,momDirZ,edep,stepLength,trackLength,rotationAngle,axialPos,processName,comptVolName,RayleighVolName,volumeID[0],volumeID[1],volumeID[2],volumeID[3],volumeID[4],volumeID[5],volumeID[6],volumeID[7],volumeID[8],volumeID[9],sourcePosX,sourcePosY,sourcePosZ,nPhantomCompton,nCrystalCompton,nPhantomRayleigh,nCrystalRayleigh,,level1ID,level2ID,level3ID,level4ID,level5ID,photonID,sourceType,decayType,gammaType
#/gate/output/tree/hits/branches/PDGEncoding/disable
#/gate/output/tree/hits/branches/trackID/disable
/gate/output/tree/hits/branches/parentID/disable
/gate/output/tree/hits/branches/trackLocalTime/disable
#/gate/output/tree/hits/branches/time/disable
/gate/output/tree/hits/branches/runID/disable
#/gate/output/tree/hits/branches/eventID/disable
/gate/output/tree/hits/branches/sourceID/disable
/gate/output/tree/hits/branches/primaryID/disable
#/gate/output/tree/hits/branches/posX/disable
#/gate/output/tree/hits/branches/posY/disable
#/gate/output/tree/hits/branches/posZ/disable
/gate/output/tree/hits/branches/localPosX/disable
/gate/output/tree/hits/branches/localPosY/disable
/gate/output/tree/hits/branches/localPosZ/disable
/gate/output/tree/hits/branches/momDirX/disable
/gate/output/tree/hits/branches/momDirY/disable
/gate/output/tree/hits/branches/momDirZ/disable
#/gate/output/tree/hits/branches/edep/disable
/gate/output/tree/hits/branches/stepLength/disable
/gate/output/tree/hits/branches/trackLength/disable
/gate/output/tree/hits/branches/rotationAngle/disable
/gate/output/tree/hits/branches/axialPos/disable
#/gate/output/tree/hits/branches/processName/disable
/gate/output/tree/hits/branches/comptVolName/disable
/gate/output/tree/hits/branches/RayleighVolName/disable
/gate/output/tree/hits/branches/sourcePosX/disable
/gate/output/tree/hits/branches/sourcePosY/disable
/gate/output/tree/hits/branches/sourcePosZ/disable
#/gate/output/tree/hits/branches/nPhantomCompton/disable
#/gate/output/tree/hits/branches/nCrystalCompton/disable
#/gate/output/tree/hits/branches/nPhantomRayleigh/disable
#/gate/output/tree/hits/branches/nCrystalRayleigh/disable
/gate/output/tree/hits/branches/photonID/disable
/gate/output/tree/hits/branches/sourceType/disable
/gate/output/tree/hits/branches/decayType/disable
/gate/output/tree/hits/branches/gammaType/disable
