/gate/source/addSource myGammaSource gps
/gate/source/myGammaSource/gps/pos/type Point
/gate/source/myGammaSource/gps/particle gamma
/gate/source/myGammaSource/gps/ene/type UserSpectrum
/gate/source/myGammaSource/gps/setSpectrumFile data/spectrum.txt
/gate/source/myGammaSource/setActivity 1000. becquerel
/gate/source/myGammaSource/gps/pos/centre 0. 0. -5. cm
/gate/source/myGammaSource/gps/ang/type iso
/gate/source/myGammaSource/gps/ang/maxtheta 180 deg
/gate/source/myGammaSource/gps/ang/mintheta 135 deg
/gate/source/myGammaSource/gps/ang/minphi 0 deg
/gate/source/myGammaSource/gps/ang/maxphi 360 deg
/gate/source/myGammaSource/attachTo world

/gate/source/myGammaSource/visualize 100 red 