#/gate/digitizerMgr/verbose 2
#/gate/digitizerMgr/convertor/verbose  3


/gate/digitizerMgr/Detector/SinglesDigitizer/Singles/insert                        adder
/gate/digitizerMgr/Detector/SinglesDigitizer/Singles/adder/positionPolicy 	      energyWeightedCentroid


/gate/digitizerMgr/Detector/SinglesDigitizer/Singles/insert                        readout
/gate/digitizerMgr/Detector/SinglesDigitizer/Singles/readout/setPolicy 	      TakeEnergyCentroid
/gate/digitizerMgr/Detector/SinglesDigitizer/Singles/readout/setDepth 	      2
/gate/digitizerMgr/Detector/SinglesDigitizer/Singles/readout/forceReadoutVolumeForEnergyCentroid    true

#/gate/digitizerMgr/Detector/SinglesDigitizer/Singles/readout/verbose 3
