#=====================================================
# point source
#=====================================================
#/gate/source/verbose 5

/gate/source/addSource sourceA PositroniumSource 
/gate/source/sourceA/gps/type Point
/gate/source/sourceA/gps/pos/centre 0 0 0 cm
/gate/source/sourceA/setActivity 1000 Bq
# Definie which positronium decay use in the simulation
/gate/source/sourceA/setType Ps
/gate/source/sourceA/setPositroniumFractions 1  
/gate/source/sourceA/setPositroniumLifetimes 142 ns 
/gate/source/sourceA/setDecayKinds k3Gamma 
# Set enable emission of deexcitation gamma ( prompt gamma ) and its energy
/gate/source/sourceA/setPromptPhotonProbabilites 1 
/gate/source/sourceA/setPromptPhotonEnergies 1000 keV


/gate/source/list
