

#=====================================================
#   D I G I T I Z E R: DETECTOR ELECTRONIC RESPONSE
#===================================================== 

/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/insert opticaladder 
/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/insert                        readout

# for crystal:
/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/readout/setDepth              1

# In order to detect only fluorescent photons, you can use an energyFraming cut:
/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/insert energyFraming
/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/energyFraming/setMax 2.1 eV
/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/energyFraming/setMin 1.77 eV

