

#=====================================================
#   D I G I T I Z E R: DETECTOR ELECTRONIC RESPONSE
#===================================================== 

/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/insert opticaladder 
/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/insert                        readout 
# for pixels:
#/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/readout/setDepth              2
# for crystal:
/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/readout/setDepth              1

# In order to detect only fluorescent photons, you can use an energyFraming cut:
/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/insert energyFraming
/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/energyFraming/setMax 2.1 eV

