#=====================================================
# point source
#=====================================================
#/gate/source/verbose 5

/gate/source/addSource sourceA Extended
/gate/source/sourceA/gps/type Point
/gate/source/sourceA/gps/pos/centre 0 0 0 cm
/gate/source/sourceA/setActivity 1000 Bq
# Definie which positronium decay use in the simulation
/gate/source/sourceA/setType oPs




/gate/source/list
