
#=====================================================
# GEOMETRY
#=====================================================

/gate/geometry/setMaterialDatabase data/GateMaterials.db

# World
/gate/world/geometry/setXLength 5 m
/gate/world/geometry/setYLength 5 m
/gate/world/geometry/setZLength 5 m
/gate/world/setMaterial Air



# Global Box
/gate/world/daughters/name             mainbox1
/gate/world/daughters/insert           box
/gate/mainbox1/geometry/setXLength 20 cm
/gate/mainbox1/geometry/setYLength 20 cm
/gate/mainbox1/geometry/setZLength 20 cm
/gate/mainbox1/placement/setTranslation 0.0 0.0 10 cm
/gate/mainbox1/setMaterial G4_WATER
/gate/mainbox1/vis/setVisible 1
/gate/mainbox1/vis/setColor blue




#=====================================================
# PHYSICS
#=====================================================

/gate/physics/addPhysicsList FTFP_INCLXX_EMZ
#/control/execute mac/physicslist_HAD_std_6_2_2.mac

/gate/physics/Gamma/SetCutInRegion      world 100 m
/gate/physics/Electron/SetCutInRegion   world 100 m
/gate/physics/Positron/SetCutInRegion   world 100 m

/gate/physics/Gamma/SetCutInRegion      mainbox1 100 m
/gate/physics/Electron/SetCutInRegion   mainbox1 100 m
/gate/physics/Positron/SetCutInRegion   mainbox1 100 m
/gate/physics/Proton/SetCutInRegion   mainbox1 0.5 mm


/gate/physics/SetMaxStepSizeInRegion world 10 mm
/gate/physics/SetMaxStepSizeInRegion mainbox1 0.5 mm
/gate/physics/ActivateStepLimiter proton
/gate/physics/ActivateStepLimiter deuteron
/gate/physics/ActivateStepLimiter triton
/gate/physics/ActivateStepLimiter alpha
/gate/physics/ActivateStepLimiter GenericIon

#/gate/physics/SetMinKineticEnergyInRegion world 10 MeV
#/gate/physics/ActivateSpecialCuts proton

/gate/physics/displayCuts


#=====================================================
# MATRIX FOR DOSE MAP OUTPUT
#=====================================================

/gate/actor/addActor                               DoseActor  doseDistribution
/gate/actor/doseDistribution/save                  output/IDD-{particleName}.mhd
/gate/actor/doseDistribution/attachTo    	   mainbox1
/gate/actor/doseDistribution/stepHitType           random
/gate/actor/doseDistribution/setPosition           0 0 0 cm
/gate/actor/doseDistribution/setResolution         1 1 200
/gate/actor/doseDistribution/saveEveryNSeconds     60
/gate/actor/doseDistribution/enableEdep            true
/gate/actor/doseDistribution/enableUncertaintyEdep false
/gate/actor/doseDistribution/enableDose            false
/gate/actor/doseDistribution/enableUncertaintyDose false
/gate/actor/doseDistribution/enableNumberOfHits    false

/gate/actor/addActor        LETActor   LETd_primaries_Actor
/gate/actor/LETd_primaries_Actor/save        output/LET_primaries-{particleName}.mhd
/gate/actor/LETd_primaries_Actor/attachTo        mainbox1
/gate/actor/LETd_primaries_Actor/stepHitType        random
/gate/actor/LETd_primaries_Actor/setPosition        0 0 0 cm
## there are two possibilities how you can score. either a cylinder axis along x direction (like in the below case, using IR1 beam model), or along the z axis. I assume the 1 and the 400 would be$
/gate/actor/LETd_primaries_Actor/setResolution    1 1 200
/gate/actor/LETd_primaries_Actor/doParallelCalculation        false
/gate/actor/LETd_primaries_Actor/setType        DoseAveraged
# /gate/actor/LETd_primaries_Actor/setOtherMaterial     G4_GRAPHITE ##   G4_AIR
/gate/actor/LETd_primaries_Actor/saveEveryNSeconds    60
/gate/actor/LETd_primaries_Actor/addFilter                       IDFilter
/gate/actor/LETd_primaries_Actor/IDFilter/selectID         1

/gate/actor/addActor        LETActor   LETt_primaries_Actor
/gate/actor/LETt_primaries_Actor/save        output/LET_primaries-{particleName}.mhd
/gate/actor/LETt_primaries_Actor/attachTo        mainbox1
/gate/actor/LETt_primaries_Actor/stepHitType        random
/gate/actor/LETt_primaries_Actor/setPosition        0 0 0 cm
## there are two possibilities how you can score. either a cylinder axis along x direction (like in the below case, using IR1 beam model), or along the z axis. I assume the 1 and the 400 would be$
/gate/actor/LETt_primaries_Actor/setResolution    1 1 200
/gate/actor/LETt_primaries_Actor/doParallelCalculation        false
/gate/actor/LETt_primaries_Actor/setType        TrackAveraged
# /gate/actor/LETt_primaries_Actor/setOtherMaterial     G4_GRAPHITE ##   G4_AIR
/gate/actor/LETt_primaries_Actor/saveEveryNSeconds    60
/gate/actor/LETt_primaries_Actor/addFilter                       IDFilter
/gate/actor/LETt_primaries_Actor/IDFilter/selectID         1
# /gate/actor/LETt_primaries_Actor/addFilter                         particleFilter
# /gate/actor/LETt_primaries_Actor/particleFilter/addParticleZ        1
# /gate/actor/LETt_primaries_Actor/particleFilter/addParticleZ        2    

        

# /gate/actor/addActor                     DoseActor  dose3d
# /gate/actor/dose3d/save                  output/carbon-3d.mhd
# /gate/actor/dose3d/attachTo    	         mainbox1
# /gate/actor/dose3d/stepHitType           random
# /gate/actor/dose3d/setPosition           0 0 0 cm
# /gate/actor/dose3d/setResolution         50 50 50
# /gate/actor/dose3d/enableEdep            true
# /gate/actor/dose3d/enableUncertaintyEdep true
# /gate/actor/dose3d/enableDose            true
# /gate/actor/dose3d/enableUncertaintyDose false
# /gate/actor/dose3d/enableNumberOfHits    true

/gate/actor/addActor               SimulationStatisticActor stat
/gate/actor/stat/save              output/stat-{particleName}.txt
/gate/actor/stat/saveEveryNSeconds 60


#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize
# Enable the following lines to display available and enabled processes
# /gate/physics/processList Available
# /gate/physics/processList Enabled


#=====================================================
# BEAMS
#=====================================================
/control/execute mac/source_{particleName}.mac

#=====================================================
# VISUALISATION & VERBOSE
#=====================================================

#/vis/disable
#/control/execute mac/visu.mac
#/control/execute mac/verbose.mac
# /gate/random/verbose 1
# /gate/source/verbose 0

#=====================================================
# START BEAMS
#=====================================================

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed 12345678910

/gate/application/noGlobalOutput

/gate/application/start
