#Docker for gate
#systemctl start docker
#login: docker login
#build: docker build -t tbaudier/gatebenchmarks -f Dockerfile_gatebenchmarks .
#push: docker push tbaudier/gatebenchmarks
#interactive: docker run -ti --rm -v $(Pipeline.Workspace)/software:/home tbaudier/gatebenchmarks /bin/bash

FROM centos:7
RUN yum install -y  make \
                    libX11-devel.x86_64 \
                    libXpm-devel.x86_64 \
                    libXft-devel.x86_64 \
                    libXext-devel.x86_64 \
                    libXmu-devel.x86_64 \
                    binutils \
                    qt5-qtbase-devel.x86_64 \
                    git \
                    cmake \
                    unzip \
                    wget \
                    mesa-libGLU-devel.x86_64 \
                    centos-release-scl \
                    python3-devel \
                    which \
                    openssl-devel \
                    patch \
 && yum install -y devtoolset-7-gcc-c++

#create folder and install cmake
RUN mkdir software \
 && cd software \
 && wget https://github.com/Kitware/CMake/releases/download/v3.18.4/cmake-3.18.4-Linux-x86_64.tar.gz \
 && tar xzvf cmake-3.18.4-Linux-x86_64.tar.gz \
 && echo "source /opt/rh/devtoolset-7/enable" >> /etc/mybashrc \
 && source /etc/mybashrc \
 && echo "export PATH=/software/cmake-3.18.4-Linux-x86_64/bin/:$PATH" >> /etc/mybashrc

#Build root
RUN mkdir software/root-cern \
 && source /etc/mybashrc \
 && cd software/root-cern \
 && mkdir src bin install \
 && git clone --branch v6-24-06 https://github.com/root-project/root.git src \
 && cd bin \
 && cmake ../src/ -DCMAKE_CXX_STANDARD=17 \
                  -Dpython=OFF \
                  -DCMAKE_INSTALL_PREFIX=/software/root-cern/install \
 && make -j16 install \
 && cd .. \
 && rm -rf bin src

#Build geant4
RUN mkdir software/geant4 \
 && source /etc/mybashrc \
 && cd software/geant4 \
 && mkdir src bin install data \
 && git clone --branch v11.2.0 https://github.com/Geant4/geant4.git src \
 && cd bin \
 && cmake ../src/ -DGEANT4_INSTALL_DATA=OFF \
                  -DGEANT4_INSTALL_DATADIR=/software/geant4/data \
                  -DGEANT4_USE_QT=ON \
                  -DGEANT4_BUILD_MULTITHREADED=OFF \
                  -DCMAKE_INSTALL_PREFIX=/software/geant4/install \
                  -DGEANT4_USE_OPENGL_X11=ON \
 && make -j16 install \
 && cd .. \
 && rm -rf bin src data

#Download Geant4 data
#Separate to avoid to push large container
RUN cd software/geant4 \
 && mkdir data \
 && wget https://cern.ch/geant4-data/datasets/G4NDL.4.7.tar.gz \
 && tar xzvf G4NDL.4.7.tar.gz \
 && rm -f G4*.tar.gz \
 && mv G4* data

RUN cd software/geant4 \
 && wget https://cern.ch/geant4-data/datasets/G4EMLOW.8.5.tar.gz \
 && tar xzvf G4EMLOW.8.5.tar.gz \
 && rm -f G4*.tar.gz \
 && mv G4* data

RUN cd software/geant4 \
 && wget https://cern.ch/geant4-data/datasets/G4PhotonEvaporation.5.7.tar.gz \
 && wget https://cern.ch/geant4-data/datasets/G4RadioactiveDecay.5.6.tar.gz \
 && wget https://cern.ch/geant4-data/datasets/G4RealSurface.2.2.tar.gz \
 && tar xzvf G4PhotonEvaporation.5.7.tar.gz \
 && tar xzvf G4RadioactiveDecay.5.6.tar.gz \
 && tar xzvf G4RealSurface.2.2.tar.gz \
 && rm -f G4*.tar.gz \
 && mv PhotonEvaporation5.7 RadioactiveDecay5.6 RealSurface2.2 data

RUN cd software/geant4 \
 && wget https://cern.ch/geant4-data/datasets/G4PARTICLEXS.4.0.tar.gz \
 && wget https://cern.ch/geant4-data/datasets/G4PII.1.3.tar.gz \
 && wget https://cern.ch/geant4-data/datasets/G4SAIDDATA.2.0.tar.gz \
 && tar xzvf G4PARTICLEXS.4.0.tar.gz \
 && tar xzvf G4PII.1.3.tar.gz \
 && tar xzvf G4SAIDDATA.2.0.tar.gz \
 && rm -f G4*.tar.gz \
 && mv G4* data

RUN cd software/geant4 \
 && wget https://cern.ch/geant4-data/datasets/G4ABLA.3.1.tar.gz \
 && wget https://cern.ch/geant4-data/datasets/G4INCL.1.2.tar.gz \
 && wget https://cern.ch/geant4-data/datasets/G4ENSDFSTATE.2.3.tar.gz \
 && tar xzvf G4ABLA.3.1.tar.gz \
 && tar xzvf G4INCL.1.2.tar.gz \
 && tar xzvf G4ENSDFSTATE.2.3.tar.gz \
 && rm -f G4*.tar.gz \
 && mv G4* data

#Prepare for gate
RUN mkdir software/gate \
 && echo "source /software/geant4/install/bin/geant4.sh" >> /etc/mybashrc \
 && echo "source /software/root-cern/install/bin/thisroot.sh" >> /etc/mybashrc \
 && source /etc/mybashrc \
 && cd software/gate \
 && mkdir src bin
 
 

